### ISSUE TITLE
How do I create a custom environment without using setfenv?

### ISSUE THREAD

**Issue by jLn0n** [RealEthanPlayzDev/LuauInLuau#3]
from [this comment](https://github.com/RealEthanPlayzDev/LuauInLuau/issues/1#issuecomment-1763302347).

also off-topic question:
how do u guys open that enormous file without lagging?

maybe pin this issue for any people needing help related to this too.

**Comment by jLn0n** [comment]
where can I access `pushcclosurek` and `setfield`?

**Comment by RealEthanPlayzDev** [comment]
You need to get them through the ``FUNC_LIST`` that will be exported (just find the c function you need on the file), use a simple editor like Notepad or Vim

As for how to construct a custom environment from scratch, I don't know the details on how to do this since I'm not really fond with C or the Lua C api, you will have to do your own research here

**Comment by jLn0n** [comment]
i have managed to add a global variable named "numba10" with its value set to `10`

here's how:
```
local LUA_GLOBALSINDEX = -10002 -- (-LUAI_MAXCSTACK - 2002)

local globalName = "numba10"
local glblNamePtr = NamedFunctionList.dlmalloc(#globalName)
rt.store.string(memory_at_0, glblNamePtr, globalName)

FUNC_LIST[806](L, 10) -- lua_pushnumber
FUNC_LIST[830](L, -10002, glblNamePtr) -- lua_setfield

NamedFunctionList.dlfree(glblNamePtr)
```

make sure to put it to the top of `LuauRunUsingCustomState` or it will not work (because the state ran without the global being defined first)

**Comment by RealEthanPlayzDev** [comment]
Perhaps I should consider exposing a method to set some simple globals (string, number, boolean)

**Comment by jLn0n** [comment]
> Perhaps I should consider exposing a method to set some simple globals (string, number, boolean), aswell as redoing how the module works, I'll keep this in mind for 0.600

please add for functions aswell.

**Comment by jLn0n** [comment]
it might need to create "wrappers" for functions accessing luau internals so we wouldn't have to wrap it in pointers and such

**Comment by RealEthanPlayzDev** [comment]
[LuauCeption](https://github.com/RealEthanPlayzDev/LuauCeption) now exports all lua c apis under export.wasm.cfns. You still have to wrap it in pointers and such however.
